-- Generated by nvimtheme.app
-- my-night-owl.lua → ~/.config/nvim/colors/my-night-owl.lua

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then vim.cmd("syntax reset") end
vim.o.background = "dark"
vim.g.colors_name = "my-night-owl"

local c = {
  bg            = "#011627",
  bg_dark       = "#01111d",
  bg_lighter    = "#0b2942",
  bg_highlight  = "#1d3b53",
  bg_visual     = "#1d3b53",
  border        = "#1e4068",
  fg            = "#d6deeb",
  fg_dim        = "#637777",
  fg_dark       = "#3d4f5e",
  cyan          = "#80cbc4",
  green         = "#addb67",
  str_col       = "#ecc48d",
  yellow        = "#ffcb8b",
  orange        = "#f78c6c",
  red           = "#ff5874",
  magenta       = "#9b15f4",
  blue          = "#7167f4",
  sky           = "#7fdbca",
  teal          = "#21c7a8",
}

local hi = function(g, o) vim.api.nvim_set_hl(0, g, o) end

-- Editor UI
hi("Normal",           { fg=c.fg,           bg=c.bg })
hi("NormalFloat",      { fg=c.fg,           bg=c.bg_lighter })
hi("NormalNC",         { fg=c.fg,           bg=c.bg_dark })
hi("SignColumn",       { fg=c.fg_dark,      bg=c.bg })
hi("CursorLine",       {                    bg=c.bg_highlight })
hi("CursorLineNr",     { fg=c.yellow,       bold=true })
hi("LineNr",           { fg=c.fg_dark })
hi("Visual",           {                    bg=c.bg_visual })
hi("MatchParen",       { fg=c.fg,           bg=c.bg_visual, bold=true })
hi("StatusLine",       { fg=c.fg,           bg=c.bg_dark })
hi("StatusLineNC",     { fg=c.fg_dim,       bg=c.bg_dark })
hi("WinSeparator",     { fg=c.border })
hi("Folded",           { fg=c.fg_dim,       bg=c.bg_highlight })
hi("Search",           { fg=c.bg_dark,      bg=c.yellow })
hi("IncSearch",        { fg=c.bg_dark,      bg=c.orange })
hi("Pmenu",            { fg=c.fg,           bg=c.bg_lighter })
hi("PmenuSel",         { fg=c.bg_dark,      bg=c.blue })
hi("FloatBorder",      { fg=c.border,       bg=c.bg_lighter })

-- Syntax
hi("Comment",          { fg=c.fg_dim,       italic=true })
hi("String",           { fg=c.str_col })
hi("Number",           { fg=c.orange })
hi("Boolean",          { fg=c.orange,       italic=true })
hi("Float",            { fg=c.orange })
hi("Constant",         { fg=c.orange })
hi("Function",         { fg=c.blue })
hi("Keyword",          { fg=c.magenta,      italic=true })
hi("Conditional",      { fg=c.magenta,      italic=true })
hi("Repeat",           { fg=c.magenta,      italic=true })
hi("Type",             { fg=c.cyan })
hi("StorageClass",     { fg=c.blue,         italic=true })
hi("Identifier",       { fg=c.fg })
hi("Operator",         { fg=c.sky })
hi("Special",          { fg=c.teal })
hi("Error",            { fg=c.red })
hi("Todo",             { fg=c.bg,           bg=c.yellow, bold=true })

-- Treesitter
hi("@variable",        { fg=c.fg })
hi("@function",        { fg=c.blue })
hi("@keyword",         { fg=c.magenta,      italic=true })
hi("@string",          { fg=c.str_col })
hi("@number",          { fg=c.orange })
hi("@type",            { fg=c.cyan })
hi("@comment",         { fg=c.fg_dim,       italic=true })
hi("@operator",        { fg=c.sky })
hi("@property",        { fg=c.fg })
hi("@tag",             { fg=c.red })
hi("@tag.attribute",   { fg=c.yellow })

-- Diagnostics
hi("DiagnosticError",  { fg=c.red })
hi("DiagnosticWarn",   { fg=c.yellow })
hi("DiagnosticInfo",   { fg=c.sky })
hi("DiagnosticHint",   { fg=c.teal })

-- Git
hi("DiffAdd",          { bg="#1e3a1e" })
hi("DiffDelete",       { fg=c.red, bg="#3a1e1e" })
hi("GitSignsAdd",      { fg=c.green })
hi("GitSignsChange",   { fg=c.blue })
hi("GitSignsDelete",   { fg=c.red })
